### PR TITLE
Finished both W2 & W3 assignments

### PR DESCRIPTION
**Pull request by QuintsGuy**
* Both commits for w2 & w3 ended up merging into a single PR
* w2 features search bar and FlatList displaying clickable images to enlarge
* w3 features navigation screens to display more details regarding an image when clicked
*  Also creates a modal when image is clicked again from inside the details screen

### CODE REVIEW

**Comment by isaaccolson** [comment]
Hey Tristan, please add screenshots or a video of the code working that hits all of the assignment's criteria.

**Comment by QuintsGuy** [comment]
https://github.com/user-attachments/assets/fc6d2fad-39a6-4aa9-a917-cbacbc1cb7c9

**Comment by QuintsGuy** [comment]
https://github.com/user-attachments/assets/3602bebb-5ae9-4895-845e-1f4635b4e421

**Comment by QuintsGuy** [comment]
https://github.com/user-attachments/assets/cebb16a7-1a76-43fe-a8de-c6effbee9e8d

Well it was stressful... but I got everything to work

**Comment by isaaccolson** [comment]
Thanks for the updates!

**Pull request merged**
